name: My First GitHub Action

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run a message
        run: echo "GitHub Action is working!"
